package:
    name: example-package
    version: 0.1.1

source:
    path: ./


requirements:
    build:
        - python

    run:
        - python

about:
  license: BSD-3
  home: http://example.com
  summary: An example package which does not contain anything
